spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # create db fellaverse manually in IDEA
    url: fellaverse.mysql.database.azure.com
    username: fella
    password: zesqiq-6ryvte-Cejxew