server:
  port: 6001
spring:
  application:
    name: provider-token
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fellaverse?serverTimeZone=UTC&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# register this microservice to eureka server
eureka:
  instance:
    hostname: localhost
    instance-id: provider-token-6001
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761
# enable eureka status, then we can access to port/actuator/info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
# springboot actuator info
info:
  app.name: microservice-token
  author: GCH

fellaverse:
  security:
    config:
      jwt:
        sign: fellaverse
        issuer: fellas
        secret: www.fellaverse.com/gch/darren/chiu/jingshuo
        expire: 600
      password:
        encrypt:
          repeat: 5
          salt: www.fellaverse.com
